# Generated by Django 2.2 on 2019-09-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegeverification',
            fields=[
                ('collegename', models.CharField(max_length=100)),
                ('collegecode', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='studentregistration',
            fields=[
                ('college_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workshop.collegeverification')),
                ('invitation_letter', models.FileField(blank=True, default='', upload_to='document/invitation/')),
                ('leader_name', models.CharField(blank=True, default='', max_length=50)),
                ('leader_id', models.FileField(blank=True, default='', upload_to='document/studentid/')),
                ('leader_mobile', models.CharField(blank=True, default='', max_length=11)),
                ('leader_email', models.EmailField(blank=True, default='', max_length=50)),
                ('member1_name', models.CharField(blank=True, default='', max_length=50)),
                ('member1_id', models.EmailField(blank=True, default='', max_length=50)),
                ('member1_mobile', models.CharField(blank=True, default='', max_length=11)),
                ('member1_file', models.FileField(blank=True, default='', upload_to='document/studentid/')),
                ('member2_name', models.CharField(blank=True, default='', max_length=50)),
                ('member2_id', models.EmailField(blank=True, default='', max_length=50)),
                ('member2_mobile', models.CharField(blank=True, default='', max_length=11)),
                ('member2_file', models.FileField(blank=True, default='', upload_to='document/studentid/')),
                ('member3_name', models.CharField(blank=True, default='', max_length=50)),
                ('member3_id', models.EmailField(blank=True, default='', max_length=50)),
                ('member3_mobile', models.CharField(blank=True, default='', max_length=11)),
                ('member3_file', models.FileField(blank=True, default='', upload_to='document/studentid/')),
                ('member4_name', models.CharField(blank=True, default='', max_length=50)),
                ('member4_id', models.EmailField(blank=True, default='', max_length=50)),
                ('member4_mobile', models.CharField(blank=True, default='', max_length=11)),
                ('member4_file', models.FileField(blank=True, default='', upload_to='document/studentid/')),
            ],
        ),
    ]
