# Generated by Django 2.0.6 on 2019-09-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.events')),
            ],
        ),
    ]
