# Generated by Django 2.0.6 on 2019-09-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_event_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_details',
            old_name='event_id',
            new_name='event_name',
        ),
    ]
