# Generated by Django 2.0.6 on 2019-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_events_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.FileField(blank=True, default='', upload_to='event/images/'),
        ),
    ]
