# Generated by Django 2.0.6 on 2019-09-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_events_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', upload_to='teams/images/')),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('short_url', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('event_image', models.FileField(blank=True, default='', upload_to='teams/thumbnail/')),
            ],
        ),
        migrations.AddField(
            model_name='team_images',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.teams'),
        ),
    ]
