# Generated by Django 2.0.6 on 2019-09-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20190913_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_images',
            name='person_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
