# Generated by Django 2.2.5 on 2019-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20190913_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_images',
            name='person_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
